apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kkambbaki-alpha-ingress
  namespace: kkambbaki-alpha
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`alpha.singun11.wtf`)
    kind: Rule
    services:
    - name: kkambbaki-alpha-nginx-static-svc
      port: 80
    middlewares:
    - name: kkambbaki-alpha-redirect-to-https
  tls:
    secretName: kkambbaki-alpha-certificate
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kkambbaki-alpha-ingress-http
  namespace: kkambbaki-alpha
spec:
  entryPoints:
  - web
  routes:
  - match: Host(`alpha.singun11.wtf`) && PathPrefix(`/.well-known/acme-challenge/`)
    kind: Rule
    services:
    - name: kkambbaki-alpha-nginx-static-svc
      port: 80
  - match: Host(`alpha.singun11.wtf`)
    kind: Rule
    services:
    - name: kkambbaki-alpha-nginx-static-svc
      port: 80
    middlewares:
    - name: kkambbaki-alpha-redirect-to-https
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: kkambbaki-alpha-redirect-to-https
  namespace: kkambbaki-alpha
spec:
  redirectScheme:
    scheme: https
    permanent: true
