apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kkambbaki-alpha-static-ingress
  namespace: kkambbaki-alpha
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`alpha.singun11.wtf`) && PathPrefix(`/static/`)
    kind: Rule
    services:
    - name: kkambbaki-alpha-nginx-static-svc
      port: 80
  - match: Host(`alpha.singun11.wtf`) && PathPrefix(`/media/`)
    kind: Rule
    services:
    - name: kkambbaki-alpha-nginx-static-svc
      port: 80
  tls:
    secretName: kkambbaki-alpha-certificate
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kkambbaki-alpha-static-ingress-http
  namespace: kkambbaki-alpha
spec:
  entryPoints:
  - web
  routes:
  - match: Host(`alpha.singun11.wtf`) && PathPrefix(`/static/`)
    kind: Rule
    services:
    - name: kkambbaki-alpha-nginx-static-svc
      port: 80
  - match: Host(`alpha.singun11.wtf`) && PathPrefix(`/media/`)
    kind: Rule
    services:
    - name: kkambbaki-alpha-nginx-static-svc
      port: 80
    middlewares:
    - name: kkambbaki-alpha-redirect-to-https
