apiVersion: v1
kind: ConfigMap
metadata:
  name: kkambbaki-alpha-config
  namespace: kkambbaki-alpha
data:
  DJANGO_SETTINGS_MODULE: "config.settings.alpha"
  DEBUG: "False"
  ALLOWED_HOSTS: "localhost,127.0.0.1,0.0.0.0,alpha.singun11.wtf"
  PORT: "8080"
